# Generated by Django 2.1 on 2018-10-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=100)),
                ('show_date', models.CharField(max_length=100)),
                ('show_location', models.CharField(max_length=100)),
            ],
        ),
    ]
