# Generated by Django 2.1.2 on 2018-11-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='dayOfPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='preRegistrationPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
