# Generated by Django 2.1.2 on 2018-11-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='combo_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
