# Generated by Django 2.0 on 2018-11-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_divisions',
            field=models.ManyToManyField(to='show.Division'),
        ),
    ]
