# Generated by Django 2.1.2 on 2018-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='fifth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='first',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='fourth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='sixth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classes',
            name='third',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='show.Division'),
        ),
    ]
