# Generated by Django 2.0.2 on 2018-10-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barn_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('coggins', models.IntegerField()),
                ('owner', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
