# Generated by Django 2.1.2 on 2018-11-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseridercombo',
            name='classes',
            field=models.ManyToManyField(blank=True, to='show.Classes'),
        ),
    ]
