# Generated by Django 2.1.2 on 2018-11-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20181102_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='combo_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
