# Generated by Django 2.1.2 on 2018-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_horseridercombo_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseridercombo',
            name='classes',
            field=models.ManyToManyField(to='show.Classes'),
        ),
    ]
