# Generated by Django 2.1.2 on 2018-11-14 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20181114_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='id',
        ),
        migrations.AddField(
            model_name='show',
            name='datename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='classes',
            field=models.ManyToManyField(to='show.Classes'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
