# Generated by Django 2.0 on 2018-11-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_show_show_divisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='classes',
            field=models.ManyToManyField(blank=True, to='show.Classes'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_divisions',
            field=models.ManyToManyField(blank=True, to='show.Division'),
        ),
    ]
