# Generated by Django 2.0 on 2018-11-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20181111_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='show.Classes'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_divisions',
            field=models.ManyToManyField(blank=True, null=True, to='show.Division'),
        ),
    ]
