# Generated by Django 2.1.2 on 2018-11-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20181114_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='datename',
            new_name='date_of_show',
        ),
    ]
