# Generated by Django 2.1 on 2018-11-29 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20181126_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horseridercombo',
            name='id',
        ),
        migrations.AlterField(
            model_name='horseridercombo',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
