# Generated by Django 2.0 on 2018-11-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20181102_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseRiderCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Horse')),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='type',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='combo_num',
        ),
        migrations.AddField(
            model_name='classes',
            name='class_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horseridercombo',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Rider'),
        ),
        migrations.AddField(
            model_name='rider',
            name='horses',
            field=models.ManyToManyField(through='show.HorseRiderCombo', to='show.Horse'),
        ),
    ]
