# Generated by Django 2.1 on 2018-10-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_rider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.IntegerField()),
                ('ridername', models.CharField(max_length=200)),
                ('horsename', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
    ]
