# Generated by Django 2.1.2 on 2018-11-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20181114_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='date_of_show',
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
