# Generated by Django 2.1 on 2018-10-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_combo'),
        ('show', '0004_classes'),
    ]

    operations = [
    ]
