# Generated by Django 2.1 on 2018-11-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20181129_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horseridercombo',
            name='classes',
        ),
    ]
