# Generated by Django 2.1 on 2018-11-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20181107_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='combo_num',
        ),
    ]
