# Generated by Django 2.1.2 on 2018-11-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_remove_horse_combo_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horseridercombo',
            name='id',
        ),
        migrations.AlterField(
            model_name='horseridercombo',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
