# Generated by Django 2.1 on 2018-10-29 14:46

from django.db import migrations, models
import show.models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_merge_20181029_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='combo',
            field=models.CharField(default=show.models.random_string, max_length=3),
        ),
    ]
