# Generated by Django 2.1 on 2018-11-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_remove_horseridercombo_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseridercombo',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='show.Classes'),
        ),
    ]
