# Generated by Django 2.1.2 on 2018-11-11 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_remove_horse_combo_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
