# Generated by Django 2.1.2 on 2018-11-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_horseridercombo_classes'),
        ('show', '0004_auto_20181128_2339'),
    ]

    operations = [
    ]
